# ==========================================
# SERVER
# ==========================================
server.port=8082

# ==========================================
# POSTGRESQL (NEON)
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-autumn-math-at9u9kd3-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dUk9Pf4QgnVL
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# HIKARI CONNECTION POOL
# ==========================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# JWT
# ==========================================
jwt.secret=SmartQueueSecretKey12345678901234567890
jwt.expiration=86400000

# ==========================================
# LOGGING
# ==========================================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE